[package]
name = "tiendadoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frankenstein = "0.9.0"
rusqlite = "0.26.3"
reqwest = { version = "0.11.7", features = ["blocking", "json"]}